import libs = \
  libsandbox%lib{sandbox} \
  libxstd%lib{xstd} \
  sol2%lib{sol2} \
  cpptrace%lib{cpptrace} \
  libsfml-graphics%lib{sfml-graphics} \
  glbinding%lib{glbinding} \
  glm%lib{glm} \

exe{lines-demo}: {hxx ixx txx cxx mxx}{**} $libs
{
  test.arguments = "$src_root/scripts/default.lua"
}

cxx.poptions =+ "-I$out_root" "-I$src_root"

# Enable sol2's builtin safety checks.
#
cxx.poptions += -DSOL_ALL_SAFETIES_ON=1
